version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      GOOGLE_CLIENT_ID: "your-google-client-id"
      GOOGLE_CLIENT_SECRET: "your-google-client-secret"
      GOOGLE_CALLBACK_URL: ""
      JWT_SECRET: "your-jwt-secret"
      DATABASE_URL: "your-database-url"
      GEMINI_API_KEY: "your-gemini-api-key"
      FRONTEND_ORIGIN: ""
    volumes:
      - ./back-end/uploads:/app/uploads

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ""
