# Kubernetes manifest for backend deployment and persistent storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-backend
  template:
    metadata:
      labels:
        app: resume-backend
    spec:
      containers:
      - name: resume-backend
        image: your-docker-repo/resume-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_URL
          value: "file:/data/resume.sqlite"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: resume-secrets
              key: jwt-secret
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: resume-secrets
              key: gemini-api-key
        volumeMounts:
        - name: resume-sqlite-pv
          mountPath: /data
        - name: uploads-pv
          mountPath: /app/uploads
      volumes:
      - name: resume-sqlite-pv
        persistentVolumeClaim:
          claimName: resume-sqlite-pvc
      - name: uploads-pv
        persistentVolumeClaim:
          claimName: uploads-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resume-sqlite-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-frontend
  template:
    metadata:
      labels:
        app: resume-frontend
    spec:
      containers:
      - name: resume-frontend
        image: your-docker-repo/resume-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: resume-frontend
spec:
  type: ClusterIP
  selector:
    app: resume-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
